### ISSUE TITLE
npm not up-to-date with repo

### ISSUE THREAD

**Issue by oliverlambson** [microsoft/gatsby-plugin-clarity#5]
The version in this repo is 1.1.0, [npm version](https://www.npmjs.com/package/gatsby-plugin-clarity) is 2 years old and 1.0.0

See [gatsby-plugin-clarity/package.json](https://github.com/microsoft/gatsby-plugin-clarity/blob/master/gatsby-plugin-clarity/package.json):

```
{
...
  "version": "1.1.0",
...
  "peerDependencies": {
    "gatsby": "^3.0.0-next.0 || ^4.0.0",
...
```

but on [npm](https://www.npmjs.com/package/gatsby-plugin-clarity?activeTab=readme):
```
Version:
1.0.0
```

**Comment by saghoneim** [comment]
Published the update to npm. 
Both are now 1.0.1. Thanks!
