### ISSUE TITLE
Support gatsby v5

### ISSUE THREAD

**Issue by oliverlambson** [microsoft/gatsby-plugin-clarity#6]
Gatsby v5 has been release and this repo stops support at v4 (and the version on npm only supports v3)

This error message displays when running `gatsby build` using gatsby v5.2.0:

```
Plugin gatsby-plugin-clarity is not compatible with your gatsby version 5.2.0 - It requires gatsby@^3.0.0-next.0
```

**Comment by saghoneim** [comment]
Now the plugin supports all Gatsby versions as of version 1.0.1.
Thanks!

**Comment by oliverlambson** [comment]
Thank you 😁
